build: add missing -DLIBFTDI1=1 when building fast.o
    $ make
    gcc -Wall -fPIC -fno-strict-aliasing -g -O2 -lftdi1  -DLIBFTDI1=1 -c support.c
    gcc -Wall -fPIC -fno-strict-aliasing -g -O2 -lftdi1  -DLIBFTDI1=1 -c mpsse.c
    gcc -Wall -fPIC -fno-strict-aliasing -g -O2 -lftdi1  -c fast.c
    In file included from fast.c:10:0:
    mpsse.h:9:18: fatal error: ftdi.h: No such file or directory
    compilation terminated.
    Makefile:32: recipe for target 'fast.o' failed
    make: *** [fast.o] Error 1